### ISSUE TITLE
Feature Request / Bounty ?

### ISSUE THREAD

**Issue by digitalml** [xwinstone/canvastable#14]
Hi @xwinstone. 

Love your project.  I've been looking for a canvas table just like this. I need to be able to do high frequency updates from an array of objects every 500ms but keeping CPU usage low. Cam this do it? 

Also I need row selection, column sorting and column re-ordering. 

Any chance I could I pay to get some of these features done and a high frequency update demo please? :)

**Comment by xwinstone** [comment]
hey, thanks for your love.

The performance is mainly depends on the size of data, if it's small size, I think it will not use many CPU when you do frequency updates. 

can you leave your email? i will contact you for the feature you mentioned.

**Comment by digitalml** [comment]
matthewlebo@gmail.com
